# Generated by Django 5.1.6 on 2025-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название номера')),
                ('description', models.TextField(verbose_name='Описание номера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Изображение номера')),
                ('room_type', models.CharField(max_length=100, verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
