# Generated by Django 4.2.1 on 2025-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Номер", "verbose_name_plural": "Номера"},
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(verbose_name="Описание номера"),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                upload_to="rooms/", verbose_name="Изображение номера"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название номера"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена за ночь"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(max_length=100, verbose_name="Тип номера"),
        ),
    ]
