# Generated by Django 4.2.1 on 2025-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="Описание услуги"),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                upload_to="services/", verbose_name="Изображение услуги"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название услуги"),
        ),
    ]
