# Generated by Django 4.2.1 on 2025-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(verbose_name="Оценка"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
        migrations.AlterField(
            model_name="review",
            name="user_name",
            field=models.CharField(max_length=100, verbose_name="Имя пользователя"),
        ),
    ]
