# Generated by Django 5.1.6 on 2025-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название изображения')),
                ('description', models.TextField(verbose_name='Описание изображения')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('section_url', models.URLField(verbose_name='Ссылка на раздел')),
            ],
            options={
                'verbose_name': 'Карта сайта',
                'verbose_name_plural': 'Карты сайта',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('image', models.ImageField(upload_to='special_offers/', verbose_name='Изображение акции')),
            ],
            options={
                'verbose_name': 'Специальное предложение',
                'verbose_name_plural': 'Специальные предложения',
                'ordering': ['title'],
            },
        ),
    ]
