# Generated by Django 4.2.1 on 2025-01-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
